### ISSUE TITLE
No requirements found in ./charts.

### ISSUE THREAD

**Issue by Klae** [lwolf/stolon-chart#10]
Encountering this issue when doing the helm dep build. I cloned the repository and issue this command.

![image](https://user-images.githubusercontent.com/19382348/33162789-4f0c7e60-d066-11e7-8d48-ea71ac814383.png)

**Comment by lwolf** [comment]
The chart does not have any requirements any more

**Comment by Klae** [comment]
How can we resolve the error?

**Comment by lwolf** [comment]
just don't run `dep build`.
Simply install
