### ISSUE TITLE
Add support for kubernetes backend

### ISSUE THREAD

**Issue by Flowkap** [lwolf/stolon-chart#18]
It'll be nice to support kubernetes backend by using configmaps as well. See https://github.com/sorintlab/stolon/commit/38ae6b13b5e161a5bfe0fbe01084ca060eaf2e76

I'm pretty new to charts and K8 in general, but if you'd like I can try it out?

**Comment by lwolf** [comment]
That's great idea, I somehow missed that feature release.
Sure, please try, feel free to ask any implementation questions here and I'll try to help

**Comment by Flowkap** [comment]
Yeah cool. Might take some days as it's the first helm chart I'm actively working on :)

**Comment by Flowkap** [comment]
I got it almost to work, but my keepers are not registering on the sentinel. See a demo commit here: 

https://github.com/Flowkap/stolon-chart/commit/062ba7c6d430085f3c0383a7bb444ff194e8924a

As i'm new to the stolon stuf I don't know why they'Re not connecting to be honest. Do not find much on that error as well, except uninitialized backend( bt that works and annotiations seem just fine)

Keeper
```
2018-03-05T14:13:49.991Z	INFO	cmd/keeper.go:964	our keeper data is not available, waiting for it to appear
```

Sentinel
```
2018-03-05T14:19:11.031Z	INFO	cmd/sentinel.go:778	trying to find initial master
2018-03-05T14:19:11.031Z	ERROR	cmd/sentinel.go:1815	failed to update cluster data	{"error": "cannot choose initial master: no keepers registered"}
```

Proxy
```
2018-03-05T14:19:20.672Z	INFO	cmd/proxy.go:234	no db object available, closing connections to master	{"db": ""}
```

**Comment by lwolf** [comment]
I need to try to run it by myself, but errors from your sentinel seems like the cluster initialisation job did not complete or failed. Did you check it?
https://github.com/lwolf/stolon-chart/blob/master/stolon/templates/cluster-create-job.yaml

It seems that you did not change init-container in that job, and it still trying to check etcd availability.

**Comment by Flowkap** [comment]
Thought to have changed everything there accordingly to the example. You're probably right. The created config map looked good though. 

Thx for the tip. I'll double check the init again.

**Comment by Flowkap** [comment]
Thought to have changed everything there accordingly to the example. You're probably right. The created config map looked good though. 

Thx for the tip. I'll double check the init again.

**Comment by Flowkap** [comment]
Did you have time to try it out? As far as I can see I changed the init accordingly. Even same result if I do it manually according to the official example. 

https://github.com/Flowkap/stolon-chart/blob/062ba7c6d430085f3c0383a7bb444ff194e8924a/stolon/templates/cluster-create-job.yaml

**Comment by lwolf** [comment]
Hi,
I did not. I was waiting for you to come back whether I pointed out to the issue correctly or not. Sorry about that.

Correct me if I'm wrong, but your cluster-create-job  is not working because of this:
```
 "command": ["/bin/sh", "-c", "while ! etcdctl --endpoints {{ .Values.store.endpoints }} cluster-health; do sleep 1 && echo -n .; done"],

```
```
{{- if eq .Values.store.backend "kubernetes" }}
 - --kube-resource-kind={{ .Values.store.kubeRessourceKind }}
{{- else }}
- --store-endpoints={{ .Values.store.endpoints }}
{{- end }}
``` 
corresponding links in the source file: 
https://github.com/Flowkap/stolon-chart/blob/062ba7c6d430085f3c0383a7bb444ff194e8924a/stolon/templates/cluster-create-job.yaml#L25

https://github.com/Flowkap/stolon-chart/blob/062ba7c6d430085f3c0383a7bb444ff194e8924a/stolon/templates/cluster-create-job.yaml#L41-L44

The point here is that you're trying to use  `.Values.store.endpoints` in init-container, but your kubernetes provider implementation does not require/provide this variable.

**Comment by Flowkap** [comment]
Both parts you mentioned are conditional for when Backend isn't kubernetes. The command executes and created a config map just fine. The DB kick not into action anyway. I compared the config map by my chart with the original one created by the stolon example and there's no difference I can see. 

I'd really appreciate of you could try and install my chart and check.

**Comment by Flowkap** [comment]
Today I tried it again. 

All deployments and pods start fine. The configmap is generated: 

```
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "stolon-cluster-queenly-meerkat-stolon",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/configmaps/stolon-cluster-queenly-meerkat-stolon",
    "uid": "af754648-31b7-11e8-b19c-0800271047e3",
    "resourceVersion": "8070",
    "creationTimestamp": "2018-03-27T12:09:22Z",
    "annotations": {
      "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"6783d587\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2018-03-27T12:09:22Z\",\"renewTime\":\"2018-03-27T12:29:05Z\",\"leaderTransitions\":0}",
      "stolon-clusterdata": "{\"FormatVersion\":1,\"Cluster\":{\"uid\":\"63373f45\",\"generation\":1,\"changeTime\":\"2018-03-27T12:09:27.279492341Z\",\"spec\":{\"additionalWalSenders\":null,\"additionalMasterReplicationSlots\":null,\"initMode\":\"new\",\"pgHBA\":null},\"status\":{\"phase\":\"initializing\"}},\"Keepers\":{},\"DBs\":{},\"Proxy\":{\"changeTime\":\"0001-01-01T00:00:00Z\",\"spec\":{},\"status\":{}}}"
    }
  }
}

```
This one is the configmap which gets created by the original example in https://github.com/sorintlab/stolon/tree/master/examples/kubernetes

```
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "stolon-cluster-kube-stolon",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/configmaps/stolon-cluster-kube-stolon",
    "uid": "1b30b4f4-31ba-11e8-b19c-0800271047e3",
    "resourceVersion": "7849",
    "creationTimestamp": "2018-03-27T12:26:42Z",
    "annotations": {
      "stolon-clusterdata": "{\"FormatVersion\":1,\"Cluster\":{\"uid\":\"0aa3338d\",\"generation\":1,\"changeTime\":\"2018-03-27T12:26:42.448649577Z\",\"spec\":{\"additionalWalSenders\":null,\"additionalMasterReplicationSlots\":null,\"initMode\":\"new\",\"pgHBA\":null},\"status\":{\"phase\":\"initializing\"}},\"Keepers\":{},\"DBs\":{},\"Proxy\":{\"changeTime\":\"0001-01-01T00:00:00Z\",\"spec\":{},\"status\":{}}}"
    }
  }
}
```

The services find all pods but the keepers don't initialize with the following recurring log: 

```
2018-03-27T12:28:47.402Z	INFO	cmd/keeper.go:964	our keeper data is not available, waiting for it to appear
```

And the proxies: 

```
2018-03-27T12:29:58.279Z	INFO	cmd/proxy.go:234	no db object available, closing connections to master	{"db": ""}
```

And sentinels:

```
2018-03-27T12:31:59.022Z	ERROR	cmd/sentinel.go:1815	failed to update cluster data	{"error": "cannot choose initial master: no keepers registered"}
2018-03-27T12:32:04.044Z	INFO	cmd/sentinel.go:778	trying to find initial master
```

As if they don't recognize the configmap. 

To be sure I also deleted all occurences in the chart concerning etcd. These are definitely not active.

**Comment by lwolf** [comment]
Trying to run it now. 
Job keeps failing with permissions issue.  Did you create any RBAC roles to make it install ?

```
$ kubectl logs -f stolon-test-stolon-pd42j
cannot get cluster data: failed to get latest version of configmap: configmaps "stolon-cluster-stolon-test-stolon" is forbidden: User "system:serviceaccount:default:default" cannot get configmaps in the namespace "default"
```

**Comment by lwolf** [comment]
got it to work. applied rbac manifests from the stolon repo with additional permission for configmaps. We should add it to the chart.

I'm seeing the same behaviour as you are. Based on the logs from the proxy it seems that initialisation does not create db for some reason. Will try to spend more time on it during weekend.

**Comment by Flowkap** [comment]
I got it fixed. Finally... 

Long story short: The app labels MUST be exactly "stolon-keeper" "stolon-proxy" and "stolon-sentinel" ... 
https://github.com/sorintlab/stolon/pull/433/commits/38ae6b13b5e161a5bfe0fbe01084ca060eaf2e76#diff-95cdd374e9440fde010ff35d65f8cf3fR54

I'll make a proper commit later today and let you know when its finished. Multiple cluster deploys worked for me at the same time this way. As I'm not sure if other variants (using etcd) need the fullname on the app labels I'll make these changes conditional as well. Also added stolon-cluster labels in some places to maintain the uniqeness of service discovery in the K( cluster itself. 

Come back to you when it's done :)

**Comment by lwolf** [comment]
Congratulations, great job!

**Comment by Flowkap** [comment]
> got it to work. applied rbac manifests from the stolon repo with additional permission for configmaps. We should add it to the chart.

I've got the same problem as you with that. Can you gimme a link to the solution? I'll apply it as well (setup works on a minikube cluster already)

**Comment by lwolf** [comment]
For RBAC you need to add configurations similar to those:
https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/role-binding.yaml
https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/role.yaml

with only difference - you need to add configmaps here:
https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/role.yaml#L19

But I can add it later, after PR will get merged (I'll review and test in during weekend)

**Comment by tirelibirefe** [comment]
Hello;
I've a bare-metal Kubernetes 1.18 and attempted to install stolon but it gives me following error:

`2020-04-11T13:31:58.388Z        INFO    cmd/keeper.go:976       our keeper data is not available, waiting for it to appear
2020-04-11T13:31:58.461Z        ERROR   cmd/keeper.go:778       failed to update keeper info    {"error": "update failed: failed to get latest version of pod: v1.Pod.ObjectMeta: v1.ObjectMeta.readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},\"k:{\\\"uid\\\":\\\"e0|..., bigger context ...|on-cluster\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"e0956964-6d30-4afb-97dc-1d0ae4500447\\\"}\":{|..."}`

I've seen many people have faced with the problem but I couldn't have found any solutions.
Is there a way to acomplish installation or a planned project to make it run?

Thanks & Regards
