### ISSUE TITLE
Fails to get installed on Rancher v2

### ISSUE THREAD

**Issue by anebi** [lwolf/stolon-chart#24]
Hello,

I try to install Stolon on Rancher v2 and i get following error:

`Installing
Helm template failed. Error: render error in "stolon/templates/secret.yaml": template: stolon/templates/secret.yaml:12:22: executing "stolon/templates/secret.yaml" at <required "A valid .V...>: error calling required: A valid .Values.superuserPassword entry is required! : exit status 1`

It stucks there. This happens even if I try to pass environment variable with the password.

Regards,
Ali Nebi

**Comment by lwolf** [comment]
Hi.
As message clearly stated: **A valid .Values.superuserPassword entry is required!**
you need to set one in the values.yaml file

**Comment by anebi** [comment]
Hi,

Yeah, it is true. But using Ranchver v2 UI we have a section (Anwers) from where we can pass the variable and already tried, but didn't work. Another thing that would be good and should be by default actually is that if there is no variable passed with password, then a random password should be generated and used, then let the process continue without fail on this stage.

I am not sure if this is a problem that should be really solved by you, i am sorry for that :)

Regards,
Ali Nebi

**Comment by anebi** [comment]
It looks like if i select template version 0.1.0 then everything works fine, but template version 0.3.0 and shows the exception. Something has changed probably in between that causes this.

**Comment by lwolf** [comment]
I'm not familiar with how things done in Rancher v2 UI, but the way helm charts work is you need to set required variables either in the `values.yaml` file or using command-line arguments. 

Having auto-generated password will help only for the first install, but you will still need to set the value to be able to upgrade/reprovision the chart.

How do you install chart (i.e. `helm install *****`)

**Comment by anebi** [comment]
I see. Thats ok. I was just curious about the problem, but it looks like this is not actually a problem of helm chart, but with Rancher and templates defined there. I do the installation thru the UI from catalog library. It allows setting all the parameters thru the UI itself. I will give a try installing it using the command instead of using the UI.
