### ISSUE TITLE
How update conf file postgresql

### ISSUE THREAD

**Issue by monmartins** [lwolf/stolon-chart#28]
How i edit and update conf  /stolon-data/postgres/postgresql.conf

**Comment by dineshba** [comment]
We should not manually edit the `postgresql.conf` because it is generated(and updated) by `stolon`. We can use `pgparameters` in `cluster_specification` to configure our `postgres`(keeper). Refer [here](https://github.com/sorintlab/stolon/blob/master/doc/postgres_parameters.md)

**Comment by dineshba** [comment]
@lwolf Shall we close this issue?

**Comment by monmartins** [comment]
Already use pgparameters but dont work.

**Comment by monmartins** [comment]
pgParameters: { shared_preload_libraries : "timescaledb"}

**Comment by lwolf** [comment]
@monmartins do you mind sharing the details?  @dineshba correctly pointed you to the way how it supposed to be done.

**Comment by monmartins** [comment]
After i add line pgParameters: { shared_preload_libraries : "timescaledb"} in values.yaml and install with helm install . appears on my screen that I still need to add the line, I enter through the kubectl exec -it pod bash and in the file /stolon/postgres/postgresql.conf it continues without being configured.

**Comment by monmartins** [comment]
Resolve edit statefulset.yaml

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STOLONCTL_PATCH
              value: "{ 'pgParameters' : {'shared_preload_libraries' : 'timescaledb' } }"
