### ISSUE TITLE
How to run stolon as Non-Root

### ISSUE THREAD

**Issue by sathyu** [lwolf/stolon-chart#29]

**Comment by sathyu** [comment]
Hello  

How can I deploy stolon as NOn-root  in production.  

I was able to deploy as root in my development box, but this will not work in prod.
Thanks

**Comment by lwolf** [comment]
What do you mean?

**Comment by Samusername** [comment]
There are environments where applications inside containers must not be executed as a root user, but as a non-root user.
Currently stolon gets executed as root user inside the container. Is there a way to make it run as non-root?

Non-root user should be used inside all of the containers: keepers, sentinel and proxy containers.
