### ISSUE TITLE
Can I use stable/etcd-operator instead of incubator/etcd 

### ISSUE THREAD

**Issue by Elexy** [lwolf/stolon-chart#3]
I ran into the rejoining issue mentioned in the docs and was wondering if it should be possible (in theory) to use the [etcd-operator](https://github.com/kubernetes/charts/tree/master/stable/etcd-operator) as the storage backend?

**Comment by lwolf** [comment]
Yes, the latest master (v0.2.0) of this chart does not require incubator/etcd anymore. So etcd could be provisioned using any suitable method.

**Comment by Elexy** [comment]
For anyone landing here, the [stable etcd-operator chart](https://github.com/kubernetes/charts/tree/master/stable/etcd-operator) works well with the is chart. It did require some name changing to resolve to the right etcd service.
