### ISSUE TITLE
Release.IsInstall not being set to true during helm install

### ISSUE THREAD

**Issue by fastjames** [lwolf/stolon-chart#5]
I was referred to Stolon while working on a helm chart for a rails app recently, and the first problem I observed was that postgres was not being initialized on the keeper pods. After reading through some blog comments, I traced the problem to this line:

https://github.com/lwolf/stolon-chart/blob/f32ceb06c7b7e9a7cae9a7432affcbbb940f30b1/stolon/templates/cluster-create-job.yaml#L1

When I comment out the line, postgres initializes and starts up normally. I am not sure why IsInstall would not be set to true, as this is the invocation I'm using for helm:

> helm install --namespace foobar --name some-release ./my-chart-dir

You asked me to file an issue, and I'm happy to do so. I will follow up with whatever else I can find out about this behavior. It does not seem like Release.IsInstall is behaving as it should.

**Comment by lwolf** [comment]
Thanks for creating a ticket, I'm on vacation (next 2 weeks) but will take a look at it as soon as I'm back

**Comment by fastjames** [comment]
I may have an answer on this. I'm currently using helm v2.1.3, and it appears that .Release.IsInstall was added in v2.2.0 (see https://github.com/kubernetes/helm/releases/tag/v2.2.0).

**Comment by lwolf** [comment]
Ah, that is definitely it. 
Helm v2.2 is stated as a required version in the Readme.
Closing it. Feel free to reopen it if you have this issue in v2.2+
